require("config.lazy")
require("config.plain")
--
--
--
--local lazypath = vim.fn.stdpath("data")  .. "/lazy/lazy.nvim"
--if not vim.loop.fs_stat(lazypath) then
--	vim.fn.system({
--		"git",
--		"clone",
--		"--filter-blob:none",
--		"https://github.com/folke/lazy.nvim.git",
--		"--branch=stable",
--		lazypath,
--	})
--end
--
--vim.opt.rtp:prepend(lazypath)
--
--require("lazy").setup({
--	"neovim/nvim-lspconfig"
--})
--
--local lspconfig = require("lspconfig")
--
--lspconfig.lua_ls.setup{
--	settings = {
--	},
--	cmd = {"/home/zc/.local/share/nvim/mason/packages/lua-language-server/lua-language-server"}
--}

